[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]
DEFMT_LOG="info"
ESP_LOG="info"

[build]
rustflags = [
  "-C", "force-frame-pointers",
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]
